name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Obrigado por abrir sua primeira issue neste projeto! 🚀 Sua contribuição é muito importante para melhorar nossa aplicação. Em breve iremos analisar sua solicitação."
        pr-message: "Parabéns pelo seu primeiro Pull Request! 🎉 Agradecemos por contribuir com este projeto. Sua colaboração ajuda a construir uma solução cada vez melhor."
